### ISSUE TITLE
Page notice: There is extra spacing in the box when the status icon is present

### ISSUE THREAD

**Issue by melquan** [eBay/skin#1143]
This was tested in Chrome.

With icon:
![image](https://user-images.githubusercontent.com/19419138/84939052-96cdb980-b092-11ea-8638-6b79240d499c.png)

Without icon:
![image](https://user-images.githubusercontent.com/19419138/84939085-a6e59900-b092-11ea-98e4-13dc2e82fc6c.png)

It appears that the user agent stylesheet applies `1.33em` to `margin-block-start` and `margin-block-end` to `h4` elements causing this extra space.

Ideally, it should be the spacing regardless of the presence of the icon or not.

**Comment by ianmcburnie** [comment]
Scope of this task is to reduce the top and bottom padding down to 16px.

Icon is permanent and should not be removed for page notice.

**Comment by ianmcburnie** [comment]
I guess we'll need to make sure it's consistent with section notice spacing too. It looks like that also has differing spacing depending on presence of icon.

![Screen Shot 2020-06-17 at 1 03 55 PM](https://user-images.githubusercontent.com/38065/84944779-27a89300-b09b-11ea-87f4-dcd513a41a8b.png)

**Comment by ianmcburnie** [comment]
Done in 10.6.0

**Comment by melquan** [comment]
Just FYI, it's still a problem for IE11 since `margin-block-*` and `margin-inline-*` properties.

**Comment by ianmcburnie** [comment]
We've completely refactored notices in v11, and I don't believe those newer properties were needed. Given this is IE11, we might just live with the layout issue according to browser policy. Having said that, I'm almost certain `margin: 0` was tried here and didn't work for some reason... I'll try and look at this again myself if I get a chance.

**Comment by melquan** [comment]
In Chrome & IE dev tools, I tried removing the previous fix and setting `margin: 0` and it seemed to work?  But let me know what you find out, for my own knowledge.
